In [1]:
from google.colab import files
uploaded = files.upload()

Saving uncleaned_netflix_titles_dataset.csv to uncleaned_netflix_titles_dataset.csv

In [2]:
import pandas as pd
import numpy as np


data = pd.read_csv('uncleaned_netflix_titles_dataset.csv', encoding='latin1')
data.head(5)
data.shape # Rows & Columns
data.columns #Column names
data.info() # Data type + nulls
data.isnull().sum() # Missing values count

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8809 entries, 0 to 8808
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8809 non-null   object
 1   type          8809 non-null   object
 2   title         8809 non-null   object
 3   director      6175 non-null   object
 4   cast          7984 non-null   object
 5   country       7978 non-null   object
 6   date_added    8799 non-null   object
 7   release_year  8809 non-null   int64
 8   rating        8805 non-null   object
 9   duration      8806 non-null   object
 10  listed_in     8809 non-null   object
 11  description   8809 non-null   object
dtypes: int64(1), object(11)
memory usage: 826.0+ KB

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [3]:
data['director'].fillna("Not Specified", inplace=True)
data['cast'].fillna("Not Specified", inplace=True)
data['country'].fillna("Unknown", inplace=True)
data['rating'].fillna("Not Rated", inplace=True)

/tmp/ipython-input-186/3749570084.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['director'].fillna("Not Specified", inplace=True)
/tmp/ipython-input-186/3749570084.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['cast'].fillna("Not Specified", inplace=True)
/tmp/ipython-input-186/3749570084.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['country'].fillna("Unknown", inplace=True)
/tmp/ipython-input-186/3749570084.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['rating'].fillna("Not Rated", inplace=True)

In [4]:
data.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           0
duration         3
listed_in        0
description      0
dtype: int64

In [5]:
# Convert Date Column Properly
# Convert date_added to datetime:

data['date_added'] = pd.to_datetime(data['date_added'], errors='coerce')
data['year_added'] = data['date_added'].dt.year
data.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Specified,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0
1,s2,TV Show,Blood & Water,Not Specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0

In [6]:
# Clean Duration Column (Important)
data[['duration_value', 'duration_type']] = data['duration'].str.split(' ', expand= True)

# Convert duration_value to numeric:
data['duration_value'] = pd.to_numeric(data['duration_value'], errors='coerce')

In [7]:
# Remove Duplicates

data = data.drop_duplicates()

In [8]:
# Strip Extra Spaces (Remove extra spaces in the column)
data.columns = data.columns.str.strip()

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8809 entries, 0 to 8808
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         8809 non-null   object
 1   type            8809 non-null   object
 2   title           8809 non-null   object
 3   director        8809 non-null   object
 4   cast            8809 non-null   object
 5   country         8809 non-null   object
 6   date_added      8711 non-null   datetime64[ns]
 7   release_year    8809 non-null   int64
 8   rating          8809 non-null   object
 9   duration        8806 non-null   object
 10  listed_in       8809 non-null   object
 11  description     8809 non-null   object
 12  year_added      8711 non-null   float64
 13  duration_value  8806 non-null   float64
 14  duration_type   8806 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(11)
memory usage: 1.0+ MB

In [10]:
data.isnull().sum()

show_id            0
type               0
title              0
director           0
cast               0
country            0
date_added        98
release_year       0
rating             0
duration           3
listed_in          0
description        0
year_added        98
duration_value     3
duration_type      3
dtype: int64

In [16]:
data = data.dropna(subset=['year_added', 'duration_value']).copy()
data['year_added'] = data['year_added'].astype(int)
data['duration_value'] = data['duration_value'].astype(int)

In [14]:
data.duplicated().sum()

np.int64(0)

In [15]:
data['duration_value'].head()

0    90
1     2
2     1
3     1
4     2
Name: duration_value, dtype: int64

In [17]:
data = data.dropna(subset=['date_added'])
data = data.dropna(subset= ['duration'])
data.isnull().sum()

show_id           0
type              0
title             0
director          0
cast              0
country           0
date_added        0
release_year      0
rating            0
duration          0
listed_in         0
description       0
year_added        0
duration_value    0
duration_type     0
dtype: int64

Data Cleaning is done!

Next EDA

In [18]:
data['type'].value_counts()

type
Movie      6129
TV Show    2579
Name: count, dtype: int64

In [19]:
# Are TV Shows increasing in recent years?

data.groupby(['year_added', 'type']).size().unstack()

type         Movie  TV Show
year_added
2008           1.0      1.0
2009           2.0      NaN
2010           1.0      NaN
2011          13.0      NaN
2012           3.0      NaN
2013           6.0      4.0
2014          19.0      4.0
2015          56.0     17.0
2016         251.0    165.0
2017         838.0    325.0
2018        1237.0    388.0
2019        1424.0    575.0
2020        1284.0    594.0
2021         993.0    505.0
2024           1.0      1.0

In [20]:
# Which country produces the most content?

data[data['country'] != 'Unknown']['country'] \
    .str.split(', ').explode() \
    .value_counts().head(10)

country
United States     3640
India             1045
United Kingdom     785
Canada             432
France             389
Japan              314
Spain              228
South Korea        227
Germany            225
Mexico             169
Name: count, dtype: int64

In [21]:
# Which country produces more TV Shows vs Movies?

data.groupby(['country', 'type']).size().unstack().sort_values(by="Movie", ascending= False)

type                                Movie  TV Show
country
United States                      2056.0    720.0
India                               893.0     78.0
Unknown                             440.0    387.0
United Kingdom                      206.0    197.0
Canada                              122.0     51.0
...                                   ...      ...
United States, New Zealand, Japan     NaN      1.0
United States, Poland                 NaN      1.0
United States, Singapore              NaN      1.0
United States, South Korea, China     NaN      2.0
Uruguay, Germany                      NaN      1.0

[746 rows x 2 columns]

In [22]:
# Your table shows many combined countries like:
# United States, New Zealand, Japan
# United States, Poland
# This means some content is co-produced.
# For deeper accuracy, you would explode countries before grouping.

country_type = data[data['country'] != "Unknown"]
country_type = country_type.assign(
    country = country_type['country'].str.split(', ')
).explode('country')

country_type.groupby(['country','type']).size().unstack().sort_values(by='Movie', ascending=False).head(10)

type             Movie  TV Show
country
United States   2749.0    891.0
India            962.0     83.0
United Kingdom   532.0    253.0
Canada           319.0    113.0
France           303.0     86.0
Germany          182.0     43.0
Spain            171.0     57.0
Japan            119.0    195.0
China            114.0     48.0
Mexico           111.0     58.0

In [23]:
# Let’s analyze ratings strategy.

data['rating'].value_counts()

rating
TV-MA        3184
TV-14        2133
TV-PG         838
R             799
PG-13         490
TV-Y7         330
TV-Y          300
PG            287
TV-G          212
NR             78
G              41
TV-Y7-FV        5
Not Rated       4
NC-17           3
UR              3
A               1
Name: count, dtype: int64

In [24]:
# Now let’s combine type + rating.
# This will show:
# Are Movies more mature?
# Are TV Shows more teen-focused?

data.groupby(['type', 'rating']).size().unstack()

rating,A,G,NC-17,NR,Not Rated,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
type,,,,,,,,,,,,,,,,
Movie,1.0,41.0,3.0,75.0,2.0,287.0,490.0,797.0,1427.0,126.0,2062.0,540.0,131.0,139.0,5.0,3.0
TV Show,NaN,NaN,NaN,3.0,2.0,NaN,NaN,2.0,706.0,86.0,1122.0,298.0,169.0,191.0,NaN,NaN

In [25]:
# Most Popular Genres
genres = data['listed_in'].str.split(', ').explode()
genres.value_counts().head(10)

listed_in
International Movies        2752
Dramas                      2427
Comedies                    1674
International TV Shows      1328
Documentaries                869
Action & Adventure           859
Independent Movies           756
TV Dramas                    739
Children & Family Movies     641
Romantic Movies              616
Name: count, dtype: int64

In [26]:
# Average Movie Duration
# Now let’s analyze movie length.

movies = data[data['type'] == 'Movie']
movies['duration_value'].describe()

count    6129.000000
mean       99.578887
std        28.288598
min         3.000000
25%        87.000000
50%        98.000000
75%       114.000000
max       312.000000
Name: duration_value, dtype: float64

In [27]:
# KPI KPI (Key Performance Indicator)
# A measurable metric that shows business performance.

# KPI 1 — Total Content
total_titles = len(data)
total_titles

# KPI 2 — Total Movies
total_movies = data[data['type'] == 'Movie'].shape[0]
total_movies

# KPI 3 — Total TV Shows
total_tv = data[data['type'] == 'TV Show'].shape[0]
total_tv

# KPI 4 — % Movies vs TV Shows
movie_percent = (total_movies / total_titles) * 100
tv_percent = (total_tv / total_titles) * 100

movie_percent, tv_percent

# KPI 5 — Top Producing Country
data[data['country'] != 'Unknown']['country'].value_counts().idxmax()

# KPI 6 — Top Genre
genres = data['listed_in'].str.split(', ').explode()
genres.value_counts().idxmax()


# KPI 7 — Dominant Rating
data['rating'].value_counts().idxmax()


# KPI 8 — Average Movie Duration
movies['duration_value'].mean()

np.float64(99.57888725730136)

In [28]:
# Export clean file

data.to_excel("cleaned_netflix.xlsx", index=False)
files.download("cleaned_netflix.xlsx")